### ISSUE TITLE
Uncaught Error: Call to a member function

### ISSUE THREAD

**Issue by shaikhnedab** [payu-india/PayUbiz_Opencart#3]
getting below error while trying to proceed with order in final order page.

``
AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Call to a member function write() on null in /var/www/html/market/catalog/controller/extension/payment/payubiz.php:204\nStack trace:\n#0 /var/www/html/market/catalog/controller/extension/payment/payubiz.php(15): ControllerExtensionPaymentPayubiz->manage_session()\n#1 /var/www/storage/modification/system/engine/action.php(79): ControllerExtensionPaymentPayubiz->index(Array)\n#2 /var/www/storage/modification/system/engine/loader.php(48): Action->execute(Object(Registry), Array)\n#3 /var/www/html/market/catalog/controller/extension/d_quickcheckout/payment.php(48): Loader->controller('extension/payme...')\n#4 /var/www/storage/modification/system/engine/action.php(79): ControllerExtensionDQuickcheckoutPayment->prepare(Array)\n#5 /var/www/storage/modification/system/engine/loader.php(48): Action->execute(Object(Registry), Array)\n#6 /var/www/html/market/catalog/controller/extension/d_quickcheckout/confirm.php(170): Loader->controller('extension/d_qui...', Array)\n#7 /var/ww...\n', referer: https://kebabnation.xyz/market/index.php?route=checkout/checkout
``

```
Opencart Verson: 3.0.3.3
PHP Version: 7.0
Apache2 
```

**Comment by shaikhnedab** [comment]
fixed this issue by upgrading to php 7.4. 
but now getting same issue as #1

**Comment by akhan78888** [comment]
I would want to know more
